### PR TITLE
Serialize null in positional arrays

### PR DESCRIPTION
**Pull request by maennchen**
Fix schmittjoh/serializer#571

PR: schmittjoh/serializer#572

### CODE REVIEW

**Comment by maennchen** [comment]
@scaytrase: Are you interested in updating your PR for this fork?

I currently get two errors (rebased on `jms-serializer/serializer/master`)


```
There were 2 failures:

1) JMS\Serializer\Tests\Serializer\JsonSerializationTest::testSerializeNullArray
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"foo":"bar","baz":null}'
+'{"foo":"bar","baz":null,"0":null}'

.../serializer-new/tests/JMS/Serializer/Tests/Serializer/BaseSerializationTest.php:117

2) JMS\Serializer\Tests\Serializer\JsonSerializationTest::testDepthExclusionStrategy
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"tree":{"children":[{"children":[{"children":[],"foo":"bar"}],"foo":"bar"}],"foo":"bar"}}'
+'{"tree":{"children":[{"children":[{"children":[null],"foo":"bar"}],"foo":"bar"}],"foo":"bar"}}'

.../serializer-new/tests/JMS/Serializer/Tests/Serializer/BaseSerializationTest.php:937
```

**Comment by scaytrase** [comment]
Yeah, the problem is that tests are common for several serializers.

**Comment by maennchen** [comment]
Why is that a problem?

**Comment by scaytrase** [comment]
The only way to fix this for me is to duplicate these tests and fix them to pass forcibly, as the expected data is not correct now (and the actual is). I'm not sure this is the *correct* way to do this.

The correct way is to review the ways data is serialized and check, whether the initial test is correct agains serializing null using other (all) formats

**Comment by scaytrase** [comment]
So, which way?

**Comment by maennchen** [comment]
I think that the initial expectations are correct.

This does look wrong: `{"foo":"bar","baz":null,"0":null}`

**Comment by scaytrase** [comment]
But my patch make this correct :) The initial problem is that

`["a", null, "c"]` is beins serialized as `["0" => "a", "2"=>"c"]` just because null is dropped and the array becomes non-contigous which is not possible in json without beign an object.

So the 
`[ null, "foo"=>"bar", "baz":null ] ` should be definetely be `{"foo":"bar","baz":null,"0":null}` if we allow *all* nulls to be serialized.

**Comment by maennchen** [comment]
It looks really strange. Am i right in this conclusions?:
 * `[ null => null, 'foo' => 'bar']` => `{"": null, "foo":"bar"}`
 * `[ null, null ]` => `[null, null]`

**Comment by scaytrase** [comment]
Yes - this way the regular `json_encode` does the things

```php
echo(json_encode([ null => null, 'foo' => 'bar'])) . PHP_EOL; // {"":null,"foo":"bar"}
echo(json_encode([ null , null])). PHP_EOL; // [null,null]
```

**Comment by maennchen** [comment]
Ok, so I'd say we change the tests.

In this case I'm wondering what the consequences of this PR are. Do we have to make a major version bump for that change?

Would it be possible to add an extra option which enables that behaviour and deprecate the old one to have the PR backwards compatible?

**Comment by scaytrase** [comment]
I've personally met this as a bug, because "setSerializeNull" flag actually does not serializes *all* nulls (i.e. in positional arrays, moreover, current behavior makes the initially positional array being named).

So, initially we should refer the documentation and answer the general question - is it a bug, or a feature. And  then we can make the decision.

**Comment by maennchen** [comment]
The documentation does not mention anything (that I've found). I've not even found a DocBlock comment describing the behaviour of the flag.

I think it is a bug.

**Comment by scaytrase** [comment]
Okay, I'll see how can I fix these two test as soon as I can. I think other tests should be inspected as well for consistent behavior

**Comment by scaytrase** [comment]
Ow, this was easier than I expected. All expected data is consolidated within the test, I've fixed those two, hope this help initially

**Comment by scaytrase** [comment]
https://travis-ci.org/schmittjoh/serializer/jobs/127434295
Those two got fixed.

**Comment by johndodev** [comment]
Hello,

thanks for the fix, will it on a bugfix release soon ? I just need to know if I wait or if I must code a bypass for some days.

**Comment by scaytrase** [comment]
You can took this fork https://github.com/jms-serializer/serializer instead of this lib. It not maintened. The fork contains some latest fixes

**Comment by johndodev** [comment]
Damn, didn't notice, it's working, thanks !

**Pull request merged**
